import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Only these hosts: every playbook rule lists exactly these in its `targets`.
export const TARGETS = ["claudecode", "cursor"];
export const SOURCE = "andrej-kolic/playbook";
const RULESYNC_VERSION = "24";

const GITIGNORE_LINES = [".rulesync/rules/.curated/", ".claude/rules/", ".cursor/rules/"];
const GENERATE = `rulesync generate -f rules -t ${TARGETS.join(",")}`;
const SCRIPTS = {
  "rules:install": `rulesync install && ${GENERATE}`,
  "rules:outdated": "rulesync install --outdated",
  "rules:update": `rulesync install --update && ${GENERATE}`,
};

function read(dir, file) {
  const path = join(dir, file);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function writeRulesyncConfig(dir) {
  if (read(dir, "rulesync.jsonc") !== null) return null;
  const config = { targets: TARGETS, features: ["rules"] };
  writeFileSync(join(dir, "rulesync.jsonc"), `${JSON.stringify(config, null, 2)}\n`);
  return "created rulesync.jsonc";
}

// pnpm 11 refuses to run rulesync until its `tldjs` dependency has a build decision.
function writeBuildDecision(dir) {
  const yaml = read(dir, "pnpm-workspace.yaml");
  if (yaml === null) {
    writeFileSync(join(dir, "pnpm-workspace.yaml"), "allowBuilds:\n  tldjs: false\n");
    return "created pnpm-workspace.yaml";
  }
  if (/^\s+tldjs:/m.test(yaml)) return null;
  const updated = /^allowBuilds:[ \t]*$/m.test(yaml)
    ? yaml.replace(/^allowBuilds:[ \t]*$/m, "allowBuilds:\n  tldjs: false")
    : `${yaml}${yaml.endsWith("\n") ? "" : "\n"}\nallowBuilds:\n  tldjs: false\n`;
  writeFileSync(join(dir, "pnpm-workspace.yaml"), updated);
  return "added tldjs build decision to pnpm-workspace.yaml";
}

function writeGitignore(dir) {
  const current = read(dir, ".gitignore") ?? "";
  const present = new Set(current.split("\n").map((line) => line.trim()));
  const missing = GITIGNORE_LINES.filter((line) => !present.has(line));
  if (missing.length === 0) return null;
  const separator = current === "" ? "" : current.endsWith("\n") ? "\n" : "\n\n";
  const block = `# playbook rules, generated by rulesync (pnpm rules:install)\n${missing.join("\n")}\n`;
  writeFileSync(join(dir, ".gitignore"), `${current}${separator}${block}`);
  return `added ${missing.join(", ")} to .gitignore`;
}

// Adds the missing scripts; warns instead of overwriting one that differs.
function writeScripts(dir) {
  const text = read(dir, "package.json");
  const pkg = JSON.parse(text);
  const lines = [];
  const added = [];
  for (const [name, script] of Object.entries(SCRIPTS)) {
    const existing = pkg.scripts?.[name];
    if (existing === undefined) added.push(name);
    else if (existing !== script) {
      lines.push(`warning: kept your existing "${name}" script; the playbook expects "${script}"`);
    }
  }
  if (added.length > 0) {
    pkg.scripts = { ...pkg.scripts, ...Object.fromEntries(added.map((name) => [name, SCRIPTS[name]])) };
    const indent = text.match(/^[ \t]+/m)?.[0] ?? 2;
    writeFileSync(join(dir, "package.json"), `${JSON.stringify(pkg, null, indent)}\n`);
    lines.unshift(`added ${added.join(", ")} to package.json scripts`);
  }
  return lines;
}

/** Rule copies left by the old `rulesync fetch` setup, which would duplicate the installed ones. */
export function findFetchedCopies(dir) {
  const rulesDir = join(dir, ".rulesync", "rules");
  if (!existsSync(rulesDir)) return [];
  return readdirSync(rulesDir)
    .filter((name) => name.endsWith(".md"))
    .filter((name) => readFileSync(join(rulesDir, name), "utf8").includes(`source: ${SOURCE} `));
}

/**
 * Writes or updates the config files the playbook needs, skipping any already set up.
 * Never overwrites an existing rulesync.jsonc or script.
 * @returns {string[]} one line per change or warning
 * @throws {Error} when `dir` has no package.json
 */
export function writeConfigFiles(dir) {
  if (read(dir, "package.json") === null) {
    throw new Error(`no package.json in ${dir}; run this from the project root`);
  }
  return [writeRulesyncConfig, writeBuildDecision, writeGitignore, writeScripts]
    .flatMap((step) => step(dir))
    .filter((line) => line !== null);
}

function pnpm(dir, args) {
  execFileSync("pnpm", args, { cwd: dir, stdio: "inherit" });
}

/**
 * Sets up the playbook's rules in the project at `dir`, then generates them. Runs pnpm.
 * @throws {Error} when old fetch-setup rule copies exist, or a pnpm command fails
 */
export function init(dir) {
  const fetched = findFetchedCopies(dir);
  if (fetched.length > 0) {
    throw new Error(
      `.rulesync/rules/ has rule copies from the old fetch setup (${fetched.join(", ")}). ` +
        "Delete them and their rules:fetch script first; init installs the same rules.",
    );
  }

  for (const line of writeConfigFiles(dir)) console.log(line);

  const pkg = JSON.parse(read(dir, "package.json"));
  if (!pkg.devDependencies?.rulesync && !pkg.dependencies?.rulesync) {
    pnpm(dir, ["add", "-D", `rulesync@${RULESYNC_VERSION}`]);
  }
  if (!read(dir, "rulesync.jsonc").includes(`"${SOURCE}"`)) {
    pnpm(dir, ["exec", "rulesync", "add", SOURCE, "--rules", "*", "--rules-path", ".rulesync/rules"]);
  }
  pnpm(dir, ["run", "rules:install"]);

  console.log(
    "\nDone. Commit rulesync.jsonc, rulesync.lock, .gitignore, package.json, pnpm-lock.yaml and pnpm-workspace.yaml.",
  );
}
