import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Only these hosts: every playbook rule lists exactly these in its `targets`.
export const TARGETS = ["claudecode", "cursor"];
export const SOURCE = "andrej-kolic/playbook";
const RULESYNC_VERSION = "24";

const GITIGNORE_LINES = [".rulesync/rules/.curated/", ".claude/rules/", ".cursor/rules/"];
const SCRIPT_NAME = "rules:install";
const SCRIPT = `rulesync install && rulesync generate -f rules -t ${TARGETS.join(",")}`;

function read(dir, file) {
  const path = join(dir, file);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function writeRulesyncConfig(dir) {
  if (read(dir, "rulesync.jsonc") !== null) return null;
  const config = { targets: TARGETS, features: ["rules"] };
  writeFileSync(join(dir, "rulesync.jsonc"), `${JSON.stringify(config, null, 2)}\n`);
  return "created rulesync.jsonc";
}

// pnpm 11 refuses to run rulesync until its `tldjs` dependency has a build decision.
function writeBuildDecision(dir) {
  const yaml = read(dir, "pnpm-workspace.yaml");
  if (yaml === null) {
    writeFileSync(join(dir, "pnpm-workspace.yaml"), "allowBuilds:\n  tldjs: false\n");
    return "created pnpm-workspace.yaml";
  }
  if (/^\s+tldjs:/m.test(yaml)) return null;
  const updated = /^allowBuilds:[ \t]*$/m.test(yaml)
    ? yaml.replace(/^allowBuilds:[ \t]*$/m, "allowBuilds:\n  tldjs: false")
    : `${yaml}${yaml.endsWith("\n") ? "" : "\n"}\nallowBuilds:\n  tldjs: false\n`;
  writeFileSync(join(dir, "pnpm-workspace.yaml"), updated);
  return "added tldjs build decision to pnpm-workspace.yaml";
}

function writeGitignore(dir) {
  const current = read(dir, ".gitignore") ?? "";
  const present = new Set(current.split("\n").map((line) => line.trim()));
  const missing = GITIGNORE_LINES.filter((line) => !present.has(line));
  if (missing.length === 0) return null;
  const separator = current === "" ? "" : current.endsWith("\n") ? "\n" : "\n\n";
  const block = `# playbook rules, generated by rulesync (pnpm ${SCRIPT_NAME})\n${missing.join("\n")}\n`;
  writeFileSync(join(dir, ".gitignore"), `${current}${separator}${block}`);
  return `added ${missing.join(", ")} to .gitignore`;
}

/** Adds the install script; returns a warning instead when a different one already exists. */
function writeScript(dir) {
  const text = read(dir, "package.json");
  const pkg = JSON.parse(text);
  const existing = pkg.scripts?.[SCRIPT_NAME];
  if (existing === SCRIPT) return null;
  if (existing !== undefined) {
    return `warning: kept your existing "${SCRIPT_NAME}" script; the playbook expects "${SCRIPT}"`;
  }
  pkg.scripts = { ...pkg.scripts, [SCRIPT_NAME]: SCRIPT };
  const indent = text.match(/^[ \t]+/m)?.[0] ?? 2;
  writeFileSync(join(dir, "package.json"), `${JSON.stringify(pkg, null, indent)}\n`);
  return `added "${SCRIPT_NAME}" script to package.json`;
}

/** Rule copies left by the old `rulesync fetch` setup, which would duplicate the installed ones. */
export function findFetchedCopies(dir) {
  const rulesDir = join(dir, ".rulesync", "rules");
  if (!existsSync(rulesDir)) return [];
  return readdirSync(rulesDir)
    .filter((name) => name.endsWith(".md"))
    .filter((name) => readFileSync(join(rulesDir, name), "utf8").includes(`source: ${SOURCE} `));
}

/**
 * Writes or updates the config files the playbook needs, skipping any already set up.
 * Never overwrites an existing rulesync.jsonc or script.
 * @returns {string[]} one line per change or warning
 */
export function writeConfigFiles(dir) {
  if (read(dir, "package.json") === null) {
    throw new Error(`no package.json in ${dir}; run this from the project root`);
  }
  return [writeRulesyncConfig, writeBuildDecision, writeGitignore, writeScript]
    .map((step) => step(dir))
    .filter((line) => line !== null);
}

function pnpm(dir, args) {
  execFileSync("pnpm", args, { cwd: dir, stdio: "inherit" });
}

/** Sets up the playbook's rules in the project at `dir`, then generates them. */
export function init(dir) {
  const fetched = findFetchedCopies(dir);
  if (fetched.length > 0) {
    throw new Error(
      `.rulesync/rules/ has rule copies from the old fetch setup (${fetched.join(", ")}). ` +
        "Delete them and their rules:fetch script first; init installs the same rules.",
    );
  }

  for (const line of writeConfigFiles(dir)) console.log(line);

  const pkg = JSON.parse(read(dir, "package.json"));
  if (!pkg.devDependencies?.rulesync && !pkg.dependencies?.rulesync) {
    pnpm(dir, ["add", "-D", `rulesync@${RULESYNC_VERSION}`]);
  }
  if (!read(dir, "rulesync.jsonc").includes(`"${SOURCE}"`)) {
    pnpm(dir, ["exec", "rulesync", "add", SOURCE, "--rules", "*", "--rules-path", ".rulesync/rules"]);
  }
  pnpm(dir, ["run", SCRIPT_NAME]);

  console.log(
    "\nDone. Commit rulesync.jsonc, rulesync.lock, .gitignore, package.json, pnpm-lock.yaml and pnpm-workspace.yaml.",
  );
}
