import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Only these hosts, and where rulesync generates each one's rules: every playbook rule lists exactly
// these in its `targets`.
const OUTPUT_DIRS = { claudecode: ".claude/rules/", cursor: ".cursor/rules/" };
export const TARGETS = Object.keys(OUTPUT_DIRS);
const RULES_DIRS = Object.values(OUTPUT_DIRS);
const CONFIG_FILE = "rulesync.jsonc";
export const LOCK_FILE = "rulesync.lock";
export const SOURCE = "andrej-kolic/playbook";
// Where the playbook keeps its rules, and where rulesync puts its fetched copy in a project.
export const RULES_PATH = ".rulesync/rules";
// Projects get the rulesync major the playbook itself runs and is tested with.
const RULESYNC_MAJOR = Number(
  JSON.parse(readFileSync(join(import.meta.dirname, "..", "package.json"), "utf8")).dependencies.rulesync.split(".")[0],
);

// Only rulesync's fetched copy: the generated rules in RULES_DIRS are committed, so
// agents that check out the repo without installing anything still get them.
const GITIGNORE_LINES = [`${RULES_PATH}/.curated/`];
const GENERATE = `rulesync generate -f rules -t ${TARGETS.join(",")}`;
const SCRIPTS = {
  "rules:install": `rulesync install && ${GENERATE}`,
  "rules:outdated": `pnpm dlx github:${SOURCE} rules --check`,
  "rules:update": `rulesync install --update && ${GENERATE}`,
};

function read(dir, file) {
  const path = join(dir, file);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function writeRulesyncConfig(dir) {
  if (read(dir, CONFIG_FILE) !== null) return null;
  const config = { targets: TARGETS, features: ["rules"] };
  writeFileSync(join(dir, CONFIG_FILE), `${JSON.stringify(config, null, 2)}\n`);
  return `created ${CONFIG_FILE}`;
}

// `/.claude/rules`, `**/.claude/rules/` and `.claude/rules/` ignore the same thing.
const normalizeIgnore = (line) => line.replace(/^(\*\*\/|\/)/, "").replace(/\/$/, "");

function lines(text) {
  return text.split(/\r?\n/).map((line) => line.trim());
}

// Appends `entries` under a `# comment` line, separated from existing content by a blank line.
function appendBlock(dir, file, comment, entries) {
  const current = read(dir, file) ?? "";
  const separator = current === "" ? "" : current.endsWith("\n") ? "\n" : "\n\n";
  writeFileSync(join(dir, file), `${current}${separator}# ${comment}\n${entries.join("\n")}\n`);
  return `added ${entries.join(", ")} to ${file}`;
}

function writeGitignore(dir) {
  const current = lines(read(dir, ".gitignore") ?? "");
  const messages = [];
  const missing = GITIGNORE_LINES.filter((line) => !current.includes(line));
  if (missing.length > 0) {
    const comment = "rulesync's fetched copy of the playbook rules; the generated ones are committed";
    messages.push(appendBlock(dir, ".gitignore", comment, missing));
  }
  // Lines from older setups that ignore the generated rules.
  const rulesDirs = RULES_DIRS.map(normalizeIgnore);
  const old = current.filter((line) => rulesDirs.includes(normalizeIgnore(line)));
  if (old.length > 0) {
    messages.push(
      `warning: .gitignore ignores the generated rules (${old.join(", ")}). Delete those lines, then ` +
        `\`git add ${RULES_DIRS.join(" ")}\` and commit; until then, agents that only check out ` +
        "the repo don't get the rules.",
    );
  }
  return messages;
}

// Files the playbook writes in a layout a formatter may rewrite: a pre-commit formatter would make
// them differ from what `rules:install` generates, and rulesync writes its config in a layout
// Prettier rejects.
const FORMATTER_IGNORED = [...RULES_DIRS, CONFIG_FILE];
const PRETTIER_CONFIG = /^(\.prettierrc(\..+)?|prettier\.config\.[cm]?[jt]s)$/;

function usesPrettier(dir) {
  const pkg = JSON.parse(read(dir, "package.json"));
  return (
    pkg.prettier !== undefined ||
    pkg.devDependencies?.prettier !== undefined ||
    pkg.dependencies?.prettier !== undefined ||
    readdirSync(dir).some((name) => PRETTIER_CONFIG.test(name))
  );
}

// Adds the generated files to .prettierignore, creating it when the project uses Prettier: Prettier 3
// reads .gitignore alongside it, and Prettier 2 never reads .gitignore, so a new file only adds ignores.
function writePrettierignore(dir) {
  const prettierignore = read(dir, ".prettierignore");
  if (prettierignore === null && !usesPrettier(dir)) return null;
  // A `!` line is the project's choice to format that path, so it counts as present and stays in charge.
  const present = lines(prettierignore ?? "").map((line) => normalizeIgnore(line.replace(/^!/, "")));
  const missing = FORMATTER_IGNORED.filter((entry) => !present.includes(normalizeIgnore(entry)));
  if (missing.length === 0) return null;
  const comment = "generated by rulesync from the playbook rules; formatting them makes rules:install show changes";
  return appendBlock(dir, ".prettierignore", comment, missing);
}

// Writes the playbook's scripts, overwriting any that differ, so a rerun updates them.
function writeScripts(dir) {
  const text = read(dir, "package.json");
  const pkg = JSON.parse(text);
  const lines = [];
  for (const [name, script] of Object.entries(SCRIPTS)) {
    const existing = pkg.scripts?.[name];
    if (existing === undefined) lines.push(`added ${name} to package.json scripts`);
    else if (existing !== script) lines.push(`replaced ${name} in package.json scripts (was: ${existing})`);
  }
  if (lines.length > 0) {
    pkg.scripts = { ...pkg.scripts, ...SCRIPTS };
    const indent = text.match(/^[ \t]+/m)?.[0] ?? 2;
    writeFileSync(join(dir, "package.json"), `${JSON.stringify(pkg, null, indent)}\n`);
  }
  return lines;
}

// Rule copies left by the old `rulesync fetch` setup, which would duplicate the installed ones.
function findFetchedCopies(dir) {
  const rulesDir = join(dir, RULES_PATH);
  if (!existsSync(rulesDir)) return [];
  return readdirSync(rulesDir)
    .filter((name) => name.endsWith(".md"))
    .filter((name) => readFileSync(join(rulesDir, name), "utf8").includes(`source: ${SOURCE} `));
}

/**
 * Lists what in the project at `dir` would make `playbook rules` clash with or delete existing files.
 * @returns {string[]} one message per problem; empty when it can run
 */
export function findBlockers(dir) {
  const blockers = [];
  const fetched = findFetchedCopies(dir);
  if (fetched.length > 0) {
    blockers.push(
      `${RULES_PATH}/ has rule copies from the old fetch setup (${fetched.join(", ")}). ` +
        "Delete them and the old rules:fetch, rules:generate and rules:install scripts, then rerun `playbook rules`; " +
        "it installs the same rules and its own scripts:\n" +
        `  git rm ${fetched.map((name) => `${RULES_PATH}/${name}`).join(" ")}\n` +
        `  pnpm pkg delete 'scripts["rules:fetch"]' 'scripts["rules:generate"]' 'scripts["rules:install"]'`,
    );
  }
  if (/"delete"\s*:\s*true/.test(read(dir, CONFIG_FILE) ?? "")) {
    blockers.push(
      `${CONFIG_FILE} sets "delete": true, which makes every generate wipe ${RULES_DIRS.join(" and ")}, ` +
        "hand-written rules included. Set it to false or remove it first.",
    );
  }
  return blockers;
}

/**
 * Whether `pkg` (a parsed package.json) needs rulesync installed or upgraded.
 * A version spec without a plain major number (a tag, git or workspace link) is left alone.
 */
export function needsRulesync(pkg) {
  const spec = pkg.devDependencies?.rulesync ?? pkg.dependencies?.rulesync;
  if (spec === undefined) return true;
  const major = spec.match(/^[\^~>=v\s]*(\d+)/)?.[1];
  return major !== undefined && Number(major) < RULESYNC_MAJOR;
}

/**
 * Writes or updates the config files the playbook needs, skipping any already set up.
 * Never overwrites an existing rulesync.jsonc; overwrites the playbook's scripts.
 * Writes .prettierignore only when it exists or the project uses Prettier.
 * @returns {string[]} one line per change or warning
 * @throws {Error} when `dir` has no package.json
 */
export function writeConfigFiles(dir) {
  if (read(dir, "package.json") === null) {
    throw new Error(`no package.json in ${dir}; run this from the project root`);
  }
  return [writeRulesyncConfig, writeGitignore, writePrettierignore, writeScripts]
    .flatMap((step) => step(dir))
    .filter((line) => line !== null);
}

function pnpm(dir, args) {
  execFileSync("pnpm", args, { cwd: dir, stdio: "inherit" });
}

/**
 * Sets up the playbook's rules in the project at `dir`, then generates them. Runs pnpm.
 * @throws {Error} when `findBlockers` reports a problem, or a pnpm command fails
 */
export function installRules(dir) {
  const blockers = findBlockers(dir);
  if (blockers.length > 0) throw new Error(blockers.join("\n"));

  const changes = writeConfigFiles(dir);
  for (const line of changes) console.log(line);

  // pnpm 11 refuses to run rulesync until its `tldjs` dependency has a build decision, which
  // approve-builds can only record once tldjs is installed; strict-dep-builds=false gets it there.
  const lenient = "--config.strict-dep-builds=false";
  if (needsRulesync(JSON.parse(read(dir, "package.json")))) {
    // In a workspace with several package globs, pnpm refuses a root-level add without this;
    // `-w` would do the same but fails outside a workspace.
    pnpm(dir, ["add", "-D", `rulesync@${RULESYNC_MAJOR}`, lenient, "--config.ignore-workspace-root-check=true"]);
  } else {
    pnpm(dir, ["install", lenient]);
  }
  pnpm(dir, ["approve-builds", "!tldjs"]);
  if (!read(dir, CONFIG_FILE).includes(`"${SOURCE}"`)) {
    pnpm(dir, ["exec", "rulesync", "add", SOURCE, "--rules", "*", "--rules-path", RULES_PATH]);
  }
  // Run directly, not via the rules:install script, which may be the project's own.
  pnpm(dir, ["exec", "rulesync", "install"]);
  pnpm(dir, ["exec", ...GENERATE.split(" ")]);

  const prettierignore = changes.some((line) => line.endsWith(" to .prettierignore")) ? [".prettierignore"] : [];
  const commit = [...RULES_DIRS, CONFIG_FILE, LOCK_FILE, ".gitignore", ...prettierignore, "package.json", "pnpm-lock.yaml"];
  console.log(`\nDone. Commit ${commit.join(", ")} and pnpm-workspace.yaml.`);
}
